/**
 * @file A code generator backend that translates the optimized QIR into Python code
 * using the Google Cirq framework, for execution on Google's quantum hardware.
 * @license Apache-2.0
 */

/**
 * Represents a code generator for Google's Cirq framework.
 * It takes a Quantum Intermediate Representation (QIR) and compiles it
 * into an executable Python script.
 */
class CirqBackend {
    /**
     * Creates a new CirqBackend instance.
     * @param {object} qir - The optimized Quantum Intermediate Representation.
     * The QIR should have a property `instructions` which is an array of
     * instruction objects.
     * Example QIR structure:
     * {
     *   instructions: [
     *     { type: 'gate', gate: 'h', targets: [0] },
     *     { type: 'gate', gate: 'cnot', controls: [0], targets: [1] },
     *     { type: 'measure', qubit: 0, target: 'result_0' }
     *   ]
     * }
     */
    constructor(qir) {
        if (!qir || !Array.isArray(qir.instructions)) {
            throw new Error("Invalid QIR object provided. It must have an 'instructions' array.");
        }
        this.qir = qir;
        this.pythonCode = [];
        this.indentationLevel = 0;
        this.qubitCount = 0;
        this.measurementKeys = new Set();
    }

    /**
     * Generates the complete Python script for the Cirq framework.
     * @param {number} repetitions - The number of times to run the circuit for simulation.
     * @returns {string} The generated Python script.
     */
    generate(repetitions = 1024) {
        this.pythonCode = [];
        this.indentationLevel = 0;

        this._preprocess();
        this._generateHeader();
        this._generateMainFunction(repetitions);
        this._generateFooter();

        return this.pythonCode.join('\n');
    }

    /**
     * Scans the QIR to determine the required number of qubits and measurement keys.
     * @private
     */
    _preprocess() {
        const qubitIndices = new Set();

        for (const instruction of this.qir.instructions) {
            if (instruction.targets) {
                instruction.targets.forEach(q => qubitIndices.add(q));
            }
            if (instruction.controls) {
                instruction.controls.forEach(q => qubitIndices.add(q));
            }
            if (instruction.type === 'measure') {
                qubitIndices.add(instruction.qubit);
                this.measurementKeys.add(instruction.target);
            }
            if (instruction.type === 'reset') {
                qubitIndices.add(instruction.target);
            }
        }

        this.qubitCount = qubitIndices.size > 0 ? Math.max(...qubitIndices) + 1 : 0;
    }

    /**
     * Generates the header of the Python script, including imports.
     * @private
     */
    _generateHeader() {
        this._addLine('# This script is auto-generated by the Q-Compiler Cirq backend.');
        this._addLine('# It translates a Quantum Intermediate Representation (QIR) into');
        this._addLine('# a Python script using the Google Cirq framework.');
        this._addLine('');
        this._addLine('import cirq');
        this._addLine('import numpy as np');
        this._addLine('');
    }

    /**
     * Generates the main function of the Python script, which defines and runs the circuit.
     * @param {number} repetitions - The number of simulation shots.
     * @private
     */
    _generateMainFunction(repetitions) {
        this._addLine('def main():');
        this._indent();
        this._addLine('"""');
        this._addLine('Defines, builds, and simulates the quantum circuit.');
        this._addLine('"""');

        if (this.qubitCount === 0) {
            this._addLine('print("Circuit is empty. No qubits were declared.")');
            this._unindent();
            return;
        }

        this._addLine('# Initialize the qubits');
        this._addLine(`qubits = cirq.LineQubit.range(${this.qubitCount})`);
        this._addLine('');
        this._addLine('# Create a circuit');
        this._addLine('circuit = cirq.Circuit()');
        this._addLine('');
        this._addLine('# --- Begin Circuit Definition ---');

        for (const instruction of this.qir.instructions) {
            this._translateInstruction(instruction);
        }

        this._addLine('# --- End Circuit Definition ---');
        this._addLine('');

        this._addLine('# Display the circuit');
        this._addLine('print("Circuit:")');
        this._addLine('print(circuit)');
        this._addLine('');

        this._addLine('# Initialize a simulator');
        this._addLine('# For execution on real hardware, this would be replaced with a');
        this._addLine('# connection to a quantum processor, e.g., cirq_google.QuantumEngine()');
        this._addLine('simulator = cirq.Simulator()');
        this._addLine('');

        this._addLine('# Simulate the circuit');
        this._addLine(`result = simulator.run(circuit, repetitions=${repetitions})`);
        this._addLine('');

        this._addLine('# Print the results');
        this._addLine('print("Simulation Results:")');
        this._addLine('print(result)');
        this._addLine('');

        if (this.measurementKeys.size > 0) {
            this._addLine('# For a more detailed breakdown of measurement outcomes:');
            const keys = Array.from(this.measurementKeys).map(k => `'${k}'`).join(', ');
            this._addLine(`print("\\nMeasurement Histograms (for keys: ${keys}):")`);
            this._addLine(`histograms = result.histograms(key=[${keys}])`);
            this._addLine('for i, key in enumerate(histograms):');
            this._indent();
            this._addLine('print(f"  Histogram for \\'{key}\\':")');
            this._addLine('print(cirq.plot_state_histogram(histograms[i]))');
            this._unindent();
        }

        this._unindent();
    }

    /**
     * Generates the footer of the Python script, which calls the main function.
     * @private
     */
    _generateFooter() {
        this._addLine('');
        this._addLine('if __name__ == "__main__":');
        this._indent();
        this._addLine('main()');
        this._unindent();
    }

    /**
     * Translates a single QIR instruction into a line of Cirq Python code.
     * @param {object} instruction - The QIR instruction object.
     * @private
     */
    _translateInstruction(instruction) {
        try {
            switch (instruction.type) {
                case 'gate':
                    this._translateGate(instruction);
                    break;
                case 'measure':
                    this._translateMeasure(instruction);
                    break;
                case 'reset':
                    this._translateReset(instruction);
                    break;
                case 'barrier':
                    this._translateBarrier(instruction);
                    break;
                default:
                    this._addLine(`# WARNING: Unsupported QIR instruction type: ${instruction.type}`);
                    break;
            }
        } catch (error) {
            this._addLine(`# ERROR: Failed to translate instruction: ${JSON.stringify(instruction)}`);
            this._addLine(`# ${error.message}`);
        }
    }

    /**
     * Translates a QIR gate instruction.
     * @param {object} instruction - The gate instruction.
     * @private
     */
    _translateGate(instruction) {
        const gateName = instruction.gate.toLowerCase();
        const targets = instruction.targets || [];
        const controls = instruction.controls || [];
        const params = instruction.params || [];

        const targetRefs = targets.map(q => `qubits[${q}]`);
        const controlRefs = controls.map(q => `qubits[${q}]`);

        let opString;

        // Handle common, inherently multi-qubit gates first
        if (['cnot', 'cx'].includes(gateName)) {
            if (controls.length !== 1 || targets.length !== 1) throw new Error('CNOT requires 1 control and 1 target.');
            opString = `cirq.CNOT(${controlRefs[0]}, ${targetRefs[0]})`;
        } else if (gateName === 'cz') {
            if (controls.length !== 1 || targets.length !== 1) throw new Error('CZ requires 1 control and 1 target.');
            opString = `cirq.CZ(${controlRefs[0]}, ${targetRefs[0]})`;
        } else if (gateName === 'swap') {
            if (controls.length > 0 || targets.length !== 2) throw new Error('SWAP requires 2 targets and no controls.');
            opString = `cirq.SWAP(${targetRefs[0]}, ${targetRefs[1]})`;
        } else if (['ccx', 'toffoli'].includes(gateName)) {
            if (controls.length !== 2 || targets.length !== 1) throw new Error('Toffoli requires 2 controls and 1 target.');
            opString = `cirq.CCX(${controlRefs[0]}, ${controlRefs[1]}, ${targetRefs[0]})`;
        } else {
            // Handle generic single-target gates with optional controls
            if (targets.length !== 1) throw new Error(`Gate '${gateName}' is expected to have 1 target in this backend.`);
            const targetRef = targetRefs[0];
            let baseGate;

            switch (gateName) {
                case 'h': baseGate = `cirq.H(${targetRef})`; break;
                case 'x': baseGate = `cirq.X(${targetRef})`; break;
                case 'y': baseGate = `cirq.Y(${targetRef})`; break;
                case 'z': baseGate = `cirq.Z(${targetRef})`; break;
                case 's': baseGate = `cirq.S(${targetRef})`; break;
                case 't': baseGate = `cirq.T(${targetRef})`; break;
                case 'rx': baseGate = `cirq.rx(${this._formatParam(params[0])}).on(${targetRef})`; break;
                case 'ry': baseGate = `cirq.ry(${this._formatParam(params[0])}).on(${targetRef})`; break;
                case 'rz': baseGate = `cirq.rz(${this._formatParam(params[0])}).on(${targetRef})`; break;
                default: throw new Error(`Unsupported base gate for generic control: '${gateName}'`);
            }

            if (controls.length > 0) {
                opString = `${baseGate}.controlled_by(${controlRefs.join(', ')})`;
            } else {
                opString = baseGate;
            }
        }

        this._addLine(`circuit.append(${opString})`);
    }

    /**
     * Translates a QIR measure instruction.
     * @param {object} instruction - The measure instruction.
     * @private
     */
    _translateMeasure(instruction) {
        const qubitRef = `qubits[${instruction.qubit}]`;
        const classicalKey = instruction.target;
        this._addLine(`circuit.append(cirq.measure(${qubitRef}, key='${classicalKey}'))`);
    }

    /**
     * Translates a QIR reset instruction.
     * @param {object} instruction - The reset instruction.
     * @private
     */
    _translateReset(instruction) {
        const qubitRef = `qubits[${instruction.target}]`;
        this._addLine(`circuit.append(cirq.ResetChannel().on(${qubitRef}))`);
    }

    /**
     * Translates a QIR barrier instruction.
     * @param {object} instruction - The barrier instruction.
     * @private
     */
    _translateBarrier(instruction) {
        const qubitRefs = (instruction.targets || []).map(q => `qubits[${q}]`);
        if (qubitRefs.length > 0) {
            this._addLine(`circuit.append(cirq.Barrier(${qubitRefs.join(', ')}))`);
        } else {
            this._addLine('# Global barrier (implicit in Cirq circuit structure)');
        }
    }

    /**
     * Formats a gate parameter, converting string representations of PI.
     * @param {string|number} param - The parameter to format.
     * @returns {string} The formatted parameter string for Python code.
     * @private
     */
    _formatParam(param) {
        if (typeof param === 'string') {
            // Replaces 'pi' with 'np.pi' and handles expressions like 'pi/2'
            return param.toLowerCase().replace(/pi/g, 'np.pi');
        }
        return String(param);
    }

    /**
     * Adds a line of code to the output, respecting the current indentation level.
     * @param {string} line - The line of code to add.
     * @private
     */
    _addLine(line) {
        const indent = '    '.repeat(this.indentationLevel);
        this.pythonCode.push(indent + line);
    }

    /**
     * Increases the indentation level for subsequent lines.
     * @private
     */
    _indent() {
        this.indentationLevel++;
    }

    /**
     * Decreases the indentation level for subsequent lines.
     * @private
     */
    _unindent() {
        if (this.indentationLevel > 0) {
            this.indentationLevel--;
        }
    }
}

module.exports = { CirqBackend };