import {
    createHash,
    createSign,
    createVerify,
    generateKeyPairSync,
    randomBytes,
    Signer,
    Verifier,
} from 'crypto';
import { runInNewContext, createContext } from 'vm';

/**
 * Custom error class for failures related to sovereignty enforcement, such as
 * invalid attestations, enclave execution failures, or trust boundary violations.
 */
export class SovereigntyError extends Error {
    constructor(message: string) {
        super(`SovereigntyEnforcementError: ${message}`);
        this.name = 'SovereigntyError';
    }
}

/**
 * Represents the cryptographic proof of a computation performed within a secure enclave.
 * This report can be sent to a third party to verify the integrity and authenticity of the result,
 * proving it was generated by trusted code running in a secure environment.
 */
export interface IAttestationReport {
    /** A unique identifier for the enclave that performed the computation. */
    enclaveId: string;
    /** The timestamp of when the computation was completed (ISO 8601 format). */
    timestamp: string;
    /** The SHA-512 hash of the code that was executed. */
    codeHash: string;
    /** The SHA-512 hash of the input data provided to the computation. */
    inputHash: string;
    /** The SHA-512 hash of the result produced by the computation. */
    resultHash: string;
    /** A unique, single-use number to prevent replay attacks. */
    nonce: string;
    /** The cryptographic signature of the report's content, signed by the Root of Trust. */
    signature: string;
}

/**
 * Configuration for creating a new secure execution enclave.
 */
export interface IEnclaveConfiguration {
    /** The maximum memory allocation for the enclave in megabytes. */
    memorySizeMB: number;
    /** A descriptive name for the enclave's purpose. */
    name: string;
}

/**
 * A simulated provider for Post-Quantum Cryptography (PQC) primitives.
 * In a real-world scenario, this would interface with hardware or a PQC library
 * like CRYSTALS-Dilithium. Here, we use standard elliptic curve cryptography (Ed25519)
 * as a performant and secure stand-in.
 */
export namespace QuantumCryptoProvider {
    const HASH_ALGORITHM = 'sha512';
    const KEY_ALGORITHM = 'ed25519';

    /**
     * Generates a hash of the given data.
     * @param data The data to hash.
     * @returns A hex-encoded SHA-512 hash string.
     */
    export function hash(data: Buffer): string {
        return createHash(HASH_ALGORITHM).update(data).digest('hex');
    }

    /**
     * Generates a new key pair using a quantum-resistant algorithm (simulated).
     * @returns An object containing the public and private keys in PEM format.
     */
    export function generateKeyPair(): { publicKey: string; privateKey: string } {
        return generateKeyPairSync(KEY_ALGORITHM, {
            publicKeyEncoding: { type: 'spki', format: 'pem' },
            privateKeyEncoding: { type: 'pkcs8', format: 'pem' },
        });
    }

    /**
     * Signs a digest with the given private key.
     * @param dataToSign The data to be signed.
     * @param privateKey The private key in PEM format.
     * @returns A hex-encoded signature string.
     */
    export function sign(dataToSign: string, privateKey: string): string {
        const signer: Signer = createSign(HASH_ALGORITHM);
        signer.update(dataToSign);
        signer.end();
        return signer.sign(privateKey, 'hex');
    }

    /**
     * Verifies a signature against the original data and a public key.
     * @param dataToVerify The data that was originally signed.
     * @param signature The signature to verify (hex-encoded).
     * @param publicKey The public key in PEM format.
     * @returns True if the signature is valid, false otherwise.
     */
    export function verify(dataToVerify: string, signature: string, publicKey: string): boolean {
        const verifier: Verifier = createVerify(HASH_ALGORITHM);
        verifier.update(dataToVerify);
        verifier.end();
        return verifier.verify(publicKey, signature, 'hex');
    }
}

/**
 * Represents a simulated secure execution enclave.
 * Code executed within this enclave is isolated from the main process using a VM sandbox,
 * preventing it from accessing unauthorized memory or system resources.
 */
class SecureEnclave {
    public readonly id: string;
    public readonly name: string;
    public readonly memorySizeMB: number;
    private isDestroyed: boolean = false;

    constructor(config: IEnclaveConfiguration) {
        this.id = `enclave-${randomBytes(16).toString('hex')}`;
        this.name = config.name;
        this.memorySizeMB = config.memorySizeMB;
    }

    /**
     * Executes code within a sandboxed environment. The code must be self-contained
     * and communicate its result by assigning a Buffer to the `u_output` global.
     * @param code The code to execute (as a Buffer).
     * @param inputData The input data for the code, available as `u_input` (as a Buffer).
     * @returns A promise that resolves with the result of the execution.
     * @throws {SovereigntyError} if the enclave is destroyed or execution fails.
     */
    public async execute(code: Buffer, inputData: Buffer): Promise<Buffer> {
        if (this.isDestroyed) {
            throw new SovereigntyError(`Cannot execute in destroyed enclave ${this.id}.`);
        }

        // The sandbox provides a controlled global scope for the untrusted code.
        const sandbox = {
            u_input: inputData,
            u_output: null as Buffer | null,
            // Provide a scoped console to prevent access to the host's console
            console: Object.create(null),
        };
        // Allow safe async primitives if needed
        sandbox.console.log = (...args: any[]) => { /* Enclave logs can be captured here if needed */ };


        const context = createContext(sandbox);

        try {
            // Execute the code in the sandboxed context with a timeout.
            await runInNewContext(code.toString('utf-8'), context, {
                timeout: 5000, // 5-second execution timeout to prevent infinite loops
                displayErrors: false,
            });

            if (!sandbox.u_output || !(sandbox.u_output instanceof Buffer)) {
                throw new Error('Execution did not produce a valid Buffer output in `u_output`.');
            }

            return sandbox.u_output;
        } catch (error: any) {
            throw new SovereigntyError(`Execution failed in enclave ${this.id}: ${error.message}`);
        }
    }

    /**
     * Marks the enclave as destroyed, making it unusable for future executions.
     */
    public destroy(): void {
        this.isDestroyed = true;
        // In a real implementation, this would trigger secure memory wiping.
    }
}

/**
 * Manages the lifecycle of secure enclaves and enforces the rules of Final Quantum Sovereignty.
 * This class acts as the central authority for trusted computing within the .u environment.
 * It is designed as a singleton to represent a single, hardware-backed Root of Trust.
 */
export class SovereigntyEnforcer {
    private static instance: SovereigntyEnforcer;

    private readonly rootOfTrust: { publicKey: string; privateKey: string };
    private readonly activeEnclaves: Map<string, SecureEnclave>;

    private constructor() {
        // In a real system, this key pair would be derived from a hardware-level secret
        // (e.g., a Physical Unclonable Function or Trusted Platform Module).
        // For this simulation, we generate it on initialization.
        this.rootOfTrust = QuantumCryptoProvider.generateKeyPair();
        this.activeEnclaves = new Map();
    }

    /**
     * Gets the singleton instance of the SovereigntyEnforcer.
     * @returns The single instance of the SovereigntyEnforcer.
     */
    public static getInstance(): SovereigntyEnforcer {
        if (!SovereigntyEnforcer.instance) {
            SovereigntyEnforcer.instance = new SovereigntyEnforcer();
        }
        return SovereigntyEnforcer.instance;
    }

    /**
     * Retrieves the public key of the Root of Trust.
     * This key is used by external parties to verify attestation reports.
     * @returns The public key in PEM format.
     */
    public getRootOfTrustPublicKey(): string {
        return this.rootOfTrust.publicKey;
    }

    /**
     * Creates and provisions a new secure execution enclave.
     * @param config The configuration for the new enclave.
     * @returns A promise that resolves with the ID of the newly created enclave.
     */
    public async createEnclave(config: IEnclaveConfiguration): Promise<string> {
        const enclave = new SecureEnclave(config);
        this.activeEnclaves.set(enclave.id, enclave);
        return enclave.id;
    }

    /**
     * Executes code securely within a specified enclave and generates an attestation report.
     * @param enclaveId The ID of the enclave to use for execution.
     * @param code The code to execute.
     * @param inputData The input data for the code.
     * @returns A promise that resolves with the execution result and a verifiable attestation report.
     * @throws {SovereigntyError} if the enclave does not exist or execution fails.
     */
    public async executeInEnclave(
        enclaveId: string,
        code: Buffer,
        inputData: Buffer
    ): Promise<{ result: Buffer; report: IAttestationReport }> {
        const enclave = this.activeEnclaves.get(enclaveId);
        if (!enclave) {
            throw new SovereigntyError(`Enclave with ID ${enclaveId} not found.`);
        }

        const result = await enclave.execute(code, inputData);

        const codeHash = QuantumCryptoProvider.hash(code);
        const inputHash = QuantumCryptoProvider.hash(inputData);
        const resultHash = QuantumCryptoProvider.hash(result);
        const nonce = randomBytes(16).toString('hex');
        const timestamp = new Date().toISOString();

        // The data to be signed for the attestation report.
        // The order and format must be consistent for verification.
        const reportContent = [
            enclaveId,
            timestamp,
            codeHash,
            inputHash,
            resultHash,
            nonce,
        ].join('|');

        const signature = QuantumCryptoProvider.sign(reportContent, this.rootOfTrust.privateKey);

        const report: IAttestationReport = {
            enclaveId,
            timestamp,
            codeHash,
            inputHash,
            resultHash,
            nonce,
            signature,
        };

        return { result, report };
    }

    /**
     * Verifies an attestation report to confirm the authenticity and integrity of a computation.
     * This method would be used by a remote client that receives a result and a report.
     * @param report The attestation report to verify.
     * @param rootOfTrustPublicKey The public key of the authority that signed the report.
     * @returns A promise that resolves to true if the report is valid, false otherwise.
     */
    public async verifyAttestation(
        report: IAttestationReport,
        rootOfTrustPublicKey: string
    ): Promise<boolean> {
        try {
            const reportContent = [
                report.enclaveId,
                report.timestamp,
                report.codeHash,
                report.inputHash,
                report.resultHash,
                report.nonce,
            ].join('|');

            return QuantumCryptoProvider.verify(reportContent, report.signature, rootOfTrustPublicKey);
        } catch (error) {
            // Any cryptographic error should result in a failed verification.
            return false;
        }
    }

    /**
     * Destroys an active enclave, securely wiping its state and releasing resources.
     * @param enclaveId The ID of the enclave to destroy.
     * @returns A promise that resolves when the enclave is destroyed.
     * @throws {SovereigntyError} if the enclave does not exist.
     */
    public async destroyEnclave(enclaveId: string): Promise<void> {
        const enclave = this.activeEnclaves.get(enclaveId);
        if (!enclave) {
            throw new SovereigntyError(`Enclave with ID ${enclaveId} not found.`);
        }
        enclave.destroy();
        this.activeEnclaves.delete(enclaveId);
    }
}